apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: home-frontend
  namespace: argocd
  labels:
    app: home
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  project: home
  sources:
    - chart: nginx
      repoURL: https://charts.bitnami.com/bitnami
      targetRevision: 21.1.1
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
      - CreateNamespace=true