apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
  labels:
    app: core
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  project: cluster-core
  sources:
    - repoURL: 'https://github.com/MichielVanHerreweghe/gitops-demo.git'
      path: clusters/staging/core/argocd/manifests
      targetRevision: HEAD
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
      - CreateNamespace=true